# step50_manualdeletions.py
# ------------------------------------------------------------
# Step 50 (v7): Manual cleanup — delete specific rows in DB
#
# Deletes rows from Escapement_PlotPipeline when EXACTLY ONE row
# matches all given field values. If 0 or >1 rows match a rule,
# that rule is skipped to avoid accidental mass deletion.
# ------------------------------------------------------------

import sqlite3
import pandas as pd
from pathlib import Path

print("🧹 Step 50 (v7): Manual cleanup — deleting rows by facility/species/Stock/date_iso/Adult_Total...")

# ------------------------------------------------------------
# DB PATH
# ------------------------------------------------------------
project_root = Path(__file__).resolve().parents[1]
db_path = project_root / "0_db" / "local.db"
print(f"🗄️ Using DB → {db_path}")

# ------------------------------------------------------------
# LOAD TABLE
# ------------------------------------------------------------
conn = sqlite3.connect(db_path)
df = pd.read_sql_query("SELECT * FROM Escapement_PlotPipeline;", conn)
print(f"✅ Loaded {len(df):,} rows from Escapement_PlotPipeline")

# Normalize column names to underscore schema if needed
rename_map = {
    "Adult Total": "Adult_Total",
    "Jack Total": "Jack_Total",
    "Total Eggtake": "Total_Eggtake",
    "On Hand Adults": "On_Hand_Adults",
    "On Hand Jacks": "On_Hand_Jacks",
    "Lethal Spawned": "Lethal_Spawned",
    "Live Spawned": "Live_Spawned",
    "Live Shipped": "Live_Shipped",
}
df = df.rename(columns=rename_map)

# ------------------------------------------------------------
# Normalize dates
# ------------------------------------------------------------
if "date_iso" in df.columns:
    df["date_iso"] = pd.to_datetime(df["date_iso"], errors="coerce")

# ------------------------------------------------------------
# MANUAL DELETION RULES
# ------------------------------------------------------------
manual_deletions = [
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Type N Coho",
        "Stock": "H",
        "date_iso": "2025-01-14",
        "Adult_Total": 24514,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Type N Coho",
        "Stock": "H",
        "date_iso": "2025-02-18",
        "Adult_Total": 20006,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-12-10",
        "Adult_Total": 829,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-12-31",
        "Adult_Total": 825,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2020-11-30",
        "Adult_Total": 1023,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2025-12-22",
        "Adult_Total": 2873,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-12-04",
        "Adult_Total": 2278,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2025-12-02",
        "Adult_Total": 2870,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2025-12-22",
        "Adult_Total": 2873,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2019-10-30",
        "Adult_Total": 7710,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2020-10-17",
        "Adult_Total": 8007,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2020-10-22",
        "Adult_Total": 7407,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2022-12-15",
        "Adult_Total": 17941,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2022-12-19",
        "Adult_Total": 17992,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2023-11-20",
        "Adult_Total": 14247,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2023-11-28",
        "Adult_Total": 14270,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Late Coho",
        "Stock": "H",
        "date_iso": "2022-03-03",
        "Adult_Total": 5321,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Late Coho",
        "Stock": "H",
        "date_iso": "2026-01-05",
        "Adult_Total": 6285,
    },
    {
        "facility": "Forks Creek Hatchery",
        "species": "Late Coho",
        "Stock": "W",
        "date_iso": "2025-01-28",
        "Adult_Total": 1223,
    },
    {
        "facility": "Baker Lake Hatchery",
        "species": "Sockeye",
        "Stock": "U",
        "date_iso": "2025-12-08",
        "Adult_Total": 10563,
    },
    {
        "facility": "Baker Lake Hatchery",
        "species": "Sockeye",
        "Stock": "U",
        "date_iso": "2023-12-22",
        "Adult_Total": 10648,
    },
    {
        "facility": "Bogachiel Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2024-02-06",
        "Adult_Total": 1344,
    },
    {
        "facility": "Bogachiel Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2015-03-04",
        "Adult_Total": 3612,
    },
    {
        "facility": "Cedar River Hatchery",
        "species": "Sockeye",
        "Stock": "U",
        "date_iso": "2024-12-19",
        "Adult_Total": 2617,
    },
    {
        "facility": "Cedar River Hatchery",
        "species": "Sockeye",
        "Stock": "U",
        "date_iso": "2021-11-24",
        "Adult_Total": 2888,
    },
    {
        "facility": "Cedar River Hatchery",
        "species": "Sockeye",
        "Stock": "U",
        "date_iso": "2023-10-29",
        "Adult_Total": 2218,
    },
    {
        "facility": "Cedar River Hatchery",
        "species": "Sockeye",
        "Stock": "U",
        "date_iso": "2024-12-30",
        "Adult_Total": 2623,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Type N Coho",
        "Stock": "H",
        "date_iso": "2025-02-28",
        "Adult_Total": 20008,
    },
    {
        "facility": "Merwin Dam FCF",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2025-09-17",
        "Adult_Total": 3226,
    },
    {
        "facility": "Merwin Dam FCF",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2025-09-23",
        "Adult_Total": 3349,
    },
    {
        "facility": "Naselle Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2016-10-25",
        "Adult_Total": 2005,
    },
    {
        "facility": "Naselle Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2021-11-23",
        "Adult_Total": 8335,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2025-09-23",
        "Adult_Total": 3471,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2024-12-26",
        "Adult_Total": 6798,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2025-01-06",
        "Adult_Total": 6832,
    },
    {
        "facility": "Voights Creek Hatchery",
        "species": "Odd Year Pink",
        "Stock": "W",
        "date_iso": "2025-11-03",
        "Adult_Total": 367,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2025-11-03",
        "Adult_Total": 26000,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2024-09-03",
        "Adult_Total": 3790,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2018-12-04",
        "Adult_Total": 8960,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2019-12-10",
        "Adult_Total": 8080,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2023-12-08",
        "Adult_Total": 25769,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2023-12-19",
        "Adult_Total": 25985,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2020-12-09",
        "Adult_Total": 422,
    },
    {
        "facility": "Sol Duc Hatchery",
        "species": "Summer Chinook",
        "Stock": "H",
        "date_iso": "2025-09-23",
        "Adult_Total": 1551,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2025-11-12",
        "Adult_Total": 881,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2016-10-31",
        "Adult_Total": 1084,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "W",
        "date_iso": "2016-10-25",
        "Adult_Total": 348,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-11-12",
        "Adult_Total": 2394,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-11-18",
        "Adult_Total": 2395,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2021-11-15",
        "Adult_Total": 2377,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-11-01",
        "Adult_Total": 451,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "W",
        "date_iso": "2019-11-12",
        "Adult_Total": 171,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "W",
        "date_iso": "2019-11-18",
        "Adult_Total": 172,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "W",
        "date_iso": "2020-10-27",
        "Adult_Total": 419,
    },
    {
        "facility": "Toutle River Hatchery",
        "species": "Fall Chinook",
        "Stock": "W",
        "date_iso": "2023-10-26",
        "Adult_Total": 133,
    },
    {
        "facility": "Skamania Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2024-08-13",
        "Adult_Total": 2045,
    },
    {
        "facility": "Wynoochee River Dam Trap",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2019-01-15",
        "Adult_Total": 835,
    },
    {
        "facility": "Wynoochee River Dam Trap",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2022-01-18",
        "Adult_Total": 1565,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Anadromous Coastal Cutthroat",
        "Stock": "H",
        "date_iso": "2019-12-31",
        "Adult_Total": 912,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-12-13",
        "Adult_Total": 460,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-12-29",
        "Adult_Total": 464,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2020-10-06",
        "Adult_Total": 596,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2020-06-03",
        "Adult_Total": 83,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2020-06-03",
        "Adult_Total": 103,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2020-06-08",
        "Adult_Total": 115,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Type N Coho",
        "Stock": "W",
        "date_iso": "2016-10-12",
        "Adult_Total": 539,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2019-05-07",
        "Adult_Total": 1203,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2019-05-13",
        "Adult_Total": 1241,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2019-05-21",
        "Adult_Total": 1252,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2019-05-28",
        "Adult_Total": 1259,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2019-06-03",
        "Adult_Total": 1260,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "W",
        "date_iso": "2023-03-14",
        "Adult_Total": 32,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "W",
        "date_iso": "2017-05-10",
        "Adult_Total": 212,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "W",
        "date_iso": "2019-05-08",
        "Adult_Total": 113,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "W",
        "date_iso": "2019-05-14",
        "Adult_Total": 116,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "W",
        "date_iso": "2019-05-17",
        "Adult_Total": 117,
    },
    {
        "facility": "Cowlitz Salmon Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "W",
        "date_iso": "2019-05-28",
        "Adult_Total": 118,
    },
    {
        "facility": "Cowlitz Trout Hatchery",
        "species": "Anadromous Coastal Cutthroat",
        "Stock": "H",
        "date_iso": "2016-11-01",
        "Adult_Total": 789,
    },
    # ------------------------------------------------------------
    # pdf_name-specific deletions (Stock_BO duplicates)
    # ------------------------------------------------------------
    {
        "pdf_name": "WA_EscapementReport_11-14-2019.pdf",
        "facility": "Cowlitz Trout Hatchery",
        "species": "Anadromous Coastal Cutthroat",
        "Stock": "H",
        "date_iso": "2019-10-21",
        "Adult_Total": 461,
    },
    {
        "pdf_name": "WA_EscapementReport_12-12-2019.pdf",
        "facility": "Cowlitz Trout Hatchery",
        "species": "Anadromous Coastal Cutthroat",
        "Stock": "H",
        "date_iso": "2019-11-25",
        "Adult_Total": 608,
    },
    {
        "pdf_name": "WA_EscapementReport_11-23-2016.pdf",
        "facility": "Tumwater Falls Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2016-11-10",
        "Adult_Total": 115,
    },
    {
        "facility": "Tumwater Falls Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2017-10-18",
        "Adult_Total": 29836,
    },
    {
        "facility": "Tumwater Falls Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2017-10-23",
        "Adult_Total": 30081,
    },
    {
        "facility": "Tumwater Falls Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-10-21",
        "Adult_Total": 8902,
    },
    {
        "facility": "Dungeness Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2018-12-27",
        "Adult_Total": 1852,
    },
    {
        "facility": "Dungeness Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2021-12-21",
        "Adult_Total": 6672,
    },
    {
        "facility": "Hurd Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2016-08-31",
        "Adult_Total": 84,
    },
    {
        "facility": "Hurd Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2024-10-02",
        "Adult_Total": 79,
    },
    {
        "facility": "Hurd Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2018-09-10",
        "Adult_Total": 32,
    },
    {
        "facility": "Hurd Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2021-10-06",
        "Adult_Total": 36,
    },
    {
        "facility": "Hurd Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2023-10-04",
        "Adult_Total": 34,
    },
    {
        "facility": "Beaver Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2023-11-15",
        "Adult_Total": 132,
    },
    {
        "facility": "Beaver Creek Hatchery",
        "species": "Type N Coho",
        "Stock": "H",
        "date_iso": "2019-10-28",
        "Adult_Total": 10,
    },
    {
        "facility": "Beaver Creek Hatchery",
        "species": "Type N Coho",
        "Stock": "W",
        "date_iso": "2024-12-04",
        "Adult_Total": 197,
    },
    {
        "facility": "Beaver Creek Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2018-01-16",
        "Adult_Total": 553,
    },
    {
        "facility": "Foster Road Trap",
        "species": "Fall Chinook",
        "Stock": "W",
        "date_iso": "2020-10-18",
        "Adult_Total": 61,
    },
    {
        "facility": "Elwha Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-10-02",
        "Adult_Total": 1906,
    },
    {
        "facility": "Morse Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2017-10-06",
        "Adult_Total": 255,
    },
    {
        "pdf_name": "WA_EscapementReport_01-02-2025.pdf",
        "facility": "Palmer Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2024-12-04",
        "Adult_Total": 118,
    },
    {
        "pdf_name": "WA_EscapementReport_01-09-2020.pdf",
        "facility": "Soos Creek Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2020-01-02",
        "Adult_Total": 129,
    },
    {
        "facility": "Soos Creek Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2020-01-08",
        "Adult_Total": 117,
    },
    {
        "pdf_name": "WA_EscapementReport_01-12-2023.pdf",
        "facility": "Soos Creek Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2023-01-04",
        "Adult_Total": 177,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2025-11-08",
        "Adult_Total": 20625,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2017-09-20",
        "Adult_Total": 2888,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2017-09-26",
        "Adult_Total": 3404,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2020-09-22",
        "Adult_Total": 356,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2020-09-29",
        "Adult_Total": 383,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2020-10-07",
        "Adult_Total": 379,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-09-20",
        "Adult_Total": 2964,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Odd Year Pink",
        "Stock": "U",
        "date_iso": "2019-09-20",
        "Adult_Total": 9587,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Odd Year Pink",
        "Stock": "U",
        "date_iso": "2019-10-01",
        "Adult_Total": 9607,
    },
    {
        "facility": "Hoodsport Hatchery",
        "species": "Odd Year Pink",
        "Stock": "U",
        "date_iso": "2023-09-20",
        "Adult_Total": 9557,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2018-12-11",
        "Adult_Total": 5866,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2019-11-18",
        "Adult_Total": 2525,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2019-12-03",
        "Adult_Total": 2523,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2021-10-25",
        "Adult_Total": 2950,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2016-11-14",
        "Adult_Total": 623,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2021-11-09",
        "Adult_Total": 1548,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2017-01-09",
        "Adult_Total": 353,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2021-01-04",
        "Adult_Total": 162,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2024-01-16",
        "Adult_Total": 146,
    },
    {
        "facility": "Humptulips Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2025-01-06",
        "Adult_Total": 398,
    },
    {
        "facility": "Kalama Falls Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2025-05-27",
        "Adult_Total": 12,
    },
    {
        "facility": "Kalama Falls Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2016-01-25",
        "Adult_Total": 659,
    },
    {
        "facility": "Kalama Falls Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2024-03-18",
        "Adult_Total": 315,
    },
    {
        "facility": "Kalama Falls Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2018-03-09",
        "Adult_Total": 75,
    },
    {
        "facility": "Lewis River Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2018-06-18",
        "Adult_Total": 859,
    },
    {
        "facility": "Lewis River Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2016-08-30",
        "Adult_Total": 133,
    },
    {
        "facility": "Lewis River Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2025-09-30",
        "Adult_Total": 392,
    },
    {
        "facility": "Lewis River Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2025-10-07",
        "Adult_Total": 394,
    },
    {
        "facility": "Lewis River Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2025-10-14",
        "Adult_Total": 395,
    },
    {
        "facility": "Lewis River Hatchery",
        "species": "Type N Coho",
        "Stock": "W",
        "date_iso": "2021-12-20",
        "Adult_Total": 632,
    },
    {
        "facility": "Lewis River Hatchery",
        "species": "Type N Coho",
        "Stock": "W",
        "date_iso": "2025-12-19",
        "Adult_Total": 254,
    },
    {
        "facility": "Merwin Dam FCF",
        "species": "Sockeye",
        "Stock": "U",
        "date_iso": "2016-07-20",
        "Adult_Total": 17,
    },
    {
        "facility": "Merwin Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2017-11-20",
        "Adult_Total": 339,
    },
    {
        "facility": "Merwin Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2022-12-12",
        "Adult_Total": 321,
    },
    {
        "facility": "Merwin Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2024-05-07",
        "Adult_Total": 111,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2019-12-04",
        "Adult_Total": 12009,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2019-12-09",
        "Adult_Total": 12160,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2017-11-28",
        "Adult_Total": 13940,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2020-11-17",
        "Adult_Total": 6415,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2020-11-24",
        "Adult_Total": 6482,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2021-11-22",
        "Adult_Total": 12158,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2022-11-22",
        "Adult_Total": 7058,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2022-11-28",
        "Adult_Total": 7057,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2023-11-22",
        "Adult_Total": 5405,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2024-11-13",
        "Adult_Total": 8565,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2025-11-12",
        "Adult_Total": 8631,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2024-09-25",
        "Adult_Total": 6330,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2019-10-09",
        "Adult_Total": 1192,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2019-10-14",
        "Adult_Total": 1193,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2019-10-23",
        "Adult_Total": 1194,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2019-10-28",
        "Adult_Total": 1195,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2023-10-11",
        "Adult_Total": 832,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2023-10-18",
        "Adult_Total": 834,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2023-10-24",
        "Adult_Total": 836,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2023-11-07",
        "Adult_Total": 837,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2023-11-22",
        "Adult_Total": 838,
    },
    {
        "facility": "Minter Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2025-10-03",
        "Adult_Total": 1721,
    },
    {
        "facility": "Naselle Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2022-12-12",
        "Adult_Total": 31972,
    },
    {
        "facility": "Naselle Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2022-12-19",
        "Adult_Total": 32001,
    },
    {
        "facility": "Naselle Hatchery",
        "species": "Late Coho",
        "Stock": "H",
        "date_iso": "2018-01-16",
        "Adult_Total": 171,
    },
    {
        "facility": "Naselle Hatchery",
        "species": "Late Coho",
        "Stock": "H",
        "date_iso": "2018-01-29",
        "Adult_Total": 168,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2019-01-23",
        "Adult_Total": 1663,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2023-12-28",
        "Adult_Total": 4907,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2023-10-12",
        "Adult_Total": 178,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2024-09-19",
        "Adult_Total": 58,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2018-01-17",
        "Adult_Total": 629,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2018-01-24",
        "Adult_Total": 640,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2018-12-26",
        "Adult_Total": 173,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2019-01-11",
        "Adult_Total": 169,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2020-12-22",
        "Adult_Total": 570,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2021-01-05",
        "Adult_Total": 631,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2021-01-13",
        "Adult_Total": 641,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2021-12-20",
        "Adult_Total": 340,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2022-01-18",
        "Adult_Total": 380,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2022-11-09",
        "Adult_Total": 115,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2023-10-12",
        "Adult_Total": 484,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2016-09-07",
        "Adult_Total": 1690,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2017-08-30",
        "Adult_Total": 2035,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2017-09-13",
        "Adult_Total": 2335,
    },
    {
        "facility": "Kendall Creek Hatchery",
        "species": "Spring Chinook",
        "Stock": "H",
        "date_iso": "2020-10-05",
        "Adult_Total": 1390,
    },
    {
        "facility": "Nemah Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2024-10-31",
        "Adult_Total": 1985,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2021-10-13",
        "Adult_Total": 185,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2021-10-27",
        "Adult_Total": 270,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2021-11-03",
        "Adult_Total": 267,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2022-11-01",
        "Adult_Total": 94,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-09-20",
        "Adult_Total": 449,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-09-27",
        "Adult_Total": 311,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-10-04",
        "Adult_Total": 278,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2024-09-18",
        "Adult_Total": 467,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2024-09-25",
        "Adult_Total": 472,
    },
    {
        "facility": "Glenwood Springs Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2024-10-16",
        "Adult_Total": 761,
    },
    {
        "facility": "Voights Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2025-11-12",
        "Adult_Total": 112,
    },
    {
        "facility": "Voights Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-10-22",
        "Adult_Total": 5089,
    },
    {
        "facility": "Voights Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2019-10-23",
        "Adult_Total": 5084,
    },
    {
        "facility": "Voights Creek Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-09-19",
        "Adult_Total": 941,
    },
    {
        "facility": "Issaquah Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2020-10-27",
        "Adult_Total": 2269,
    },
    {
        "facility": "Issaquah Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-11-14",
        "Adult_Total": 5741,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2017-11-21",
        "Adult_Total": 158,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2017-11-28",
        "Adult_Total": 161,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2018-11-21",
        "Adult_Total": 3451,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2022-11-22",
        "Adult_Total": 39286,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2017-11-15",
        "Adult_Total": 1800,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2025-11-17",
        "Adult_Total": 2157,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2025-11-24",
        "Adult_Total": 2167,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Late Coho",
        "Stock": "W",
        "date_iso": "2023-01-10",
        "Adult_Total": 248,
    },
    {
        "facility": "Bingham Creek Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2016-03-22",
        "Adult_Total": 552,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2020-12-09",
        "Adult_Total": 18736,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2024-01-03",
        "Adult_Total": 25988,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Summer Chinook",
        "Stock": "W",
        "date_iso": "2021-11-01",
        "Adult_Total": 102,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Summer Chinook",
        "Stock": "W",
        "date_iso": "2023-10-10",
        "Adult_Total": 74,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Summer Chinook",
        "Stock": "W",
        "date_iso": "2024-09-24",
        "Adult_Total": 82,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Summer Chinook",
        "Stock": "W",
        "date_iso": "2025-10-07",
        "Adult_Total": 65,
    },
    {
        "facility": "Marblemount Hatchery",
        "species": "Summer Chinook",
        "Stock": "W",
        "date_iso": "2025-10-24",
        "Adult_Total": 76,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2020-10-20",
        "Adult_Total": 9078,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2016-10-24",
        "Adult_Total": 22076,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2020-10-13",
        "Adult_Total": 3411,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2021-10-02",
        "Adult_Total": 17562,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2022-10-18",
        "Adult_Total": 28325,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2022-10-25",
        "Adult_Total": 28026,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-10-04",
        "Adult_Total": 20831,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2023-10-05",
        "Adult_Total": 20860,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "H",
        "date_iso": "2024-10-02",
        "Adult_Total": 13656,
    },
    {
        "facility": "George Adams Hatchery",
        "species": "Fall Chinook",
        "Stock": "W",
        "date_iso": "2022-10-25",
        "Adult_Total": 349,
    },
    {
        "facility": "Tokul Creek Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2023-01-25",
        "Adult_Total": 126,
    },
    {
        "facility": "Sol Duc Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2017-12-27",
        "Adult_Total": 18299,
    },
    {
        "facility": "Whitehorse Pond",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2018-03-10",
        "Adult_Total": 154,
    },
    {
        "facility": "Whitehorse Pond",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2019-02-20",
        "Adult_Total": 74,
    },
    {
        "facility": "Dayton Acclimation Pond",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2024-03-28",
        "Adult_Total": 214,
    },
    {
        "facility": "Tucannon Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2016-08-29",
        "Adult_Total": 105,
    },
    {
        "facility": "Tucannon Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2016-09-06",
        "Adult_Total": 106,
    },
    {
        "facility": "Tucannon Hatchery",
        "species": "Spring Chinook",
        "Stock": "W",
        "date_iso": "2016-09-09",
        "Adult_Total": 110,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Chum",
        "Stock": "U",
        "date_iso": "2023-12-07",
        "Adult_Total": 99,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2016-12-01",
        "Adult_Total": 8067,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2017-12-26",
        "Adult_Total": 4566,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2018-11-27",
        "Adult_Total": 4125,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2020-12-10",
        "Adult_Total": 8754,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "H",
        "date_iso": "2023-01-02",
        "Adult_Total": 14150,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2025-12-08",
        "Adult_Total": 1263,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2025-12-17",
        "Adult_Total": 1276,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Coho",
        "Stock": "W",
        "date_iso": "2024-11-20",
        "Adult_Total": 322,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Summer Chinook",
        "Stock": "H",
        "date_iso": "2018-09-25",
        "Adult_Total": 4985,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Summer Chinook",
        "Stock": "H",
        "date_iso": "2019-09-30",
        "Adult_Total": 4614,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Summer Chinook",
        "Stock": "H",
        "date_iso": "2024-10-02",
        "Adult_Total": 6641,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Summer Chinook",
        "Stock": "H",
        "date_iso": "2024-10-09",
        "Adult_Total": 6662,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Summer Chinook",
        "Stock": "W",
        "date_iso": "2021-10-12",
        "Adult_Total": 174,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Summer Chinook",
        "Stock": "W",
        "date_iso": "2021-10-15",
        "Adult_Total": 176,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2016-03-08",
        "Adult_Total": 129,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2024-07-08",
        "Adult_Total": 93,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2025-02-25",
        "Adult_Total": 74,
    },
    {
        "facility": "Wallace River Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2025-03-10",
        "Adult_Total": 77,
    },
    {
        "facility": "Skamania Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2021-08-21",
        "Adult_Total": 215,
    },
    {
        "facility": "Skamania Hatchery",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2021-08-28",
        "Adult_Total": 216,
    },
    {
        "facility": "Skamania Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2016-02-27",
        "Adult_Total": 1028,
    },
    {
        "facility": "Skamania Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2018-02-28",
        "Adult_Total": 436,
    },
    {
        "facility": "Skamania Hatchery",
        "species": "Winter Steelhead",
        "Stock": "H",
        "date_iso": "2018-03-14",
        "Adult_Total": 438,
    },
    {
        "facility": "Skamania Hatchery",
        "species": "Winter-Late Steelhead",
        "Stock": "W",
        "date_iso": "2020-05-16",
        "Adult_Total": 36,
    },
    {
        "facility": "Washougal Hatchery",
        "species": "Type N Coho",
        "Stock": "H",
        "date_iso": "2020-12-15",
        "Adult_Total": 4841,
    },
    {
        "facility": "Washougal Hatchery",
        "species": "Type N Coho",
        "Stock": "H",
        "date_iso": "2021-01-05",
        "Adult_Total": 5047,
    },
    {
        "facility": "Washougal Hatchery",
        "species": "Type N Coho",
        "Stock": "H",
        "date_iso": "2025-12-16",
        "Adult_Total": 2929,
    },
    {
        "facility": "Tacoma Power – Wynoochee River",
        "species": "Summer Steelhead",
        "Stock": "H",
        "date_iso": "2022-10-11",
        "Adult_Total": 97,
    },
    {
        "facility": "Wynoochee River Dam Trap",
        "species": "Winter-Late Steelhead",
        "Stock": "H",
        "date_iso": "2020-03-17",
        "Adult_Total": 660,
    },

]

# ------------------------------------------------------------
# MATCH & DELETE
# ------------------------------------------------------------
delete_indices = set()

for rule in manual_deletions:
    cond = pd.Series(True, index=df.index)

    for col, val in rule.items():
        if col not in df.columns:
            print(f"⚠️ Column '{col}' missing — skipping rule: {rule}")
            cond &= False
            continue

        if col == "date_iso":
            val = pd.to_datetime(val, errors="coerce")

        cond &= (df[col] == val)

    matches = df[cond]

    if len(matches) == 0:
        print(f"⚠️ No match found for → {rule}")
    elif len(matches) == 1:
        idx = matches.index[0]
        delete_indices.add(idx)
        print(f"🗑️ Deleting row → {rule}")
    else:
        print(f"⛔ WARNING — {len(matches)} matches found, skipping rule to avoid mass deletion.")
        print(matches)

# ------------------------------------------------------------
# APPLY DELETIONS
# ------------------------------------------------------------
before = len(df)
df = df.drop(index=delete_indices).reset_index(drop=True)
after = len(df)
removed = before - after

# ------------------------------------------------------------
# WRITE BACK TO DATABASE
# ------------------------------------------------------------
df.to_sql("Escapement_PlotPipeline", conn, if_exists="replace", index=False)
conn.close()

print("------------------------------------------------------------")
print(f"✅ Manual cleanup complete!")
print(f"🧽 Rows removed: {removed:,}")
print(f"📊 Remaining rows: {after:,}")
print("------------------------------------------------------------")
