# lookup_maps.py
# ------------------------------------------------------------
# Centralized reference data for The Run Report processing pipeline
# ------------------------------------------------------------

# --- Species Headers ---
species_headers = [
    "Fall Chinook", 
    "Spring Chinook", 
    "Summer Chinook",
    "Coho", 
    "Summer Steelhead", 
    "Sockeye", 
    "Late Coho", 
    "Summer Coho",
    "Type N Coho", "Type S Coho", "Chum", "Odd Year Pink", "Summer Chum", "Pink",
    "Summer Pink", "Winter Steelhead", "Winter-Late Steelhead", "Fall Chum",
    "Anadromous Coastal Cutthroat", "Lahontan Cutthroat", "Westslope Cutthroat",
    "Dolly/Bull Trout", "Whitefish", "Late Kokanee", "Kokanee",
    "Sucker: General", "Northern Pikeminnow"
]

# --- Family Map ---
family_map = {
    "fall chinook": "Chinook", 
    "spring chinook": "Chinook", 
    "summer chinook": "Chinook",
    "late coho": "Coho", 
    "summer coho": "Coho", 
    "type n coho": "Coho", 
    "type s coho": "Coho", 
    "coho": "Coho",
    "summer steelhead": "Steelhead", 
    "winter steelhead": "Steelhead", 
    "winter-late steelhead": "Steelhead", 
    "steelhead": "Steelhead",
    "sockeye": "Sockeye", 
    "chum": "Chum", 
    "summer chum": "Chum", 
    "fall chum": "Chum",
    "pink": "Pink", 
    "summer pink": "Pink", 
    "odd year pink": "Pink",
    "dolly/bull trout": "Bull Trout", 
    "whitefish": "Whitefish",
    "sucker: general": "Sucker", 
    "kokanee": "Kokanee", 
    "late kokanee": "Kokanee",
    "northern pikeminnow": "Pikeminnow",
    "anadromous coastal cutthroat": "Cutthroat", 
    "lahontan cutthroat": "Cutthroat", 
    "westslope cutthroat": "Cutthroat"
}

# --- Hatchery Name Normalization Map ---
hatch_name_map = {
    "GEORGE ADAMS HATCHERY": "George Adams Hatchery",
    "GEORGE ADAMS HATCHRY": "George Adams Hatchery",
    "HOODSPORT HATCHERY": "Hoodsport Hatchery",
    "SOOS CREEK HATCHERY": "Soos Creek Hatchery",
    "CR HATCHERY": "Soos Creek Hatchery",
    "ICY CR HATCHERY": "Icy Creek Hatchery",
    "PALMER HATCHERY": "Palmer Hatchery",
    "GARRISON HATCHERY": "Garrison Hatchery",
    "MINTER CR HATCHERY": "Minter Creek Hatchery",
    "NASELLE HATCHERY": "Naselle Hatchery",
    "FOSTER RD TRAP": "Foster Road Trap",
    "BEAVER CR HATCHERY": "Beaver Creek Hatchery",
    "ELOCHOMAN SILL TRAP": "Elochoman Sill Trap",
    "COWLITZ SALMON HATCHERY": "Cowlitz Salmon Hatchery",
    "COWLITZ SALMON HATCH": "Cowlitz Salmon Hatchery",
    "COWLITZ TROUT HATCH": "Cowlitz Trout Hatchery",
    "COWLITZ SALMON": "Cowlitz Salmon Hatchery",
    "KALAMA FALLS HATCHRY": "Kalama Falls Hatchery",
    "KALAMA FALLS HATCHERY": "Kalama Falls Hatchery",
    "FALLS HATCHERY": "Kalama Falls Hatchery",
    "FALLERT CR HATCHERY": "Fallert Creek Hatchery",
    "MODROW TRAP": "Modrow Trap",
    "LEWIS RIVER HATCHERY": "Lewis River Hatchery",
    "MERWIN DAM FCF": "Merwin Dam FCF",
    "MERWIN HATCHERY": "Merwin Hatchery",
    "SPEELYAI HATCHERY": "Speelyai Hatchery",
    "LYONS FERRY HATCHERY": "Lyons Ferry Hatchery",
    "MARBLEMOUNT HATCHERY": "Marblemount Hatchery",
    "HURD CR HATCHERY": "Hurd Creek Hatchery",
    "DUNGENESS HATCHERY": "Dungeness Hatchery",
    "DAYTON ACCLIMA. POND": "Dayton Acclimation Pond",
    "TUCANNON HATCHERY": "Tucannon Hatchery",
    "EASTBANK HATCHERY": "Eastbank Hatchery",
    "CHIWAWA HATCHERY": "Chiwawa Hatchery",
    "SUNSET FALLS FCF": "Sunset Falls FCF",
    "WALLACE R HATCHERY": "Wallace River Hatchery",
    "SOLDUC HATCHERY": "Sol Duc Hatchery",
    "KENDALL CR HATCHERY": "Kendall Creek Hatchery",
    "BAKER LK HATCHERY": "Baker Lake Hatchery",
    "CEDAR RIVER HATCHERY": "Cedar River Hatchery",
    "REITER PONDS": "Reiter Ponds",
    "BOGACHIEL HATCHERY": "Bogachiel Hatchery",
    "WASHOUGAL HATCHERY": "Washougal Hatchery",
    "WASHOUGAL RIVER": "Washougal Hatchery",
    "WASHOUGAL RIVER FISH": "Washougal River Weir",
    "WASHOUGAL RIVER FISH WEIR": "Washougal River Weir",
    "SKAMANIA HATCHERY": "Skamania Hatchery",
    "WHATCOM CR HATCHERY": "Whatcom Creek Hatchery",
    "SAMISH HATCHERY": "Samish Hatchery",
    "TOKUL CR HATCHERY": "Tokul Creek Hatchery",
    "ISSAQUAH HATCHERY": "Issaquah Hatchery",
    "VOIGHTS CR HATCHERY": "Voights Creek Hatchery",
    "TUMWATER FALLS HATCH": "Tumwater Falls Hatchery",
    "TUMWATER FALLS HATCHERY": "Tumwater Falls Hatchery",
    "TUMWATER FALLS": "Tumwater Falls Hatchery",
    "GLENWOOD SPRINGS": "Glenwood Springs Hatchery",
    "MORSE CREEK HATCHERY": "Morse Creek Hatchery",
    "ELWHA HATCHERY": "Elwha Hatchery",
    "HUMPTULIPS HATCHERY": "Humptulips Hatchery",
    "MAYR BROTHERS REARIN": "Mayr Brothers Rearing",
    "LK ABERDEEN HATCHERY": "Lake Aberdeen Hatchery",
    "WYNOOCHEE R DAM TRAP": "Wynoochee River Dam Trap",
    "TACOMA POWER": "Tacoma Power – Wynoochee River",
    "BINGHAM CR HATCHERY": "Bingham Creek Hatchery",
    "SATSOP SPRINGS PONDS": "Satsop Springs Ponds",
    "FORKS CREEK HATCHERY": "Forks Creek Hatchery",
    "NEMAH HATCHERY": "Nemah Hatchery",
    "GRAYS RIVER HATCHERY": "Grays River Hatchery",
    "NORTH TOUTLE HATCHRY": "Toutle River Hatchery",
    "NORTH TOUTLE HATCHERY": "Toutle River Hatchery",
    "PRIEST RAPIDS HATCHERY": "Priest Rapids Hatchery",
    "RINGOLD SPRINGS HATCHERY": "Ringold Springs Hatchery",
    "RINGOLD SPRINGS": "Ringold Springs Hatchery",
    "METHOW HATCHERY": "Methow Hatchery",
    "WHITEHORSE POND": "Whitehorse Pond",
    "WELLS HATCHERY": "Wells Hatchery",
    "SKOOKUMCHUCK HATCHERY": "Skookumchuck Hatchery",
    "SKOOKUMCHUCK HATCHRY": "Skookumchuck Hatchery",
    "MCKERNAN HATCHERY": "McKernan Hatchery",
    "CHELAN HATCHERY": "Chelan Hatchery",
    "CHELAN PUD HATCHERY": "Chelan Hatchery",
    "SPOKANE HATCHERY": "Spokane Hatchery",
    "LK WHATCOM HATCHERY": "Lake Whatcom Hatchery",
    "OMAK HATCHERY": "Omak Hatchery",
    "TWISP ACCLIMATION PD": "Twisp Acclimation Pond",
    "COTTONWOOD CR POND":"Cottonwood Creek Pond",
    "GRAYS RIVER WEIR":"Grays River Weir",
    "Eells Springs":"Eells Springs Hatchery",
}

# --- Basin Map ---
basin_map = {
    "GEORGE ADAMS HATCHERY": "Skokomish River",
    "GEORGE ADAMS HATCHRY": "Skokomish River",
    "HOODSPORT HATCHERY": "Hood Canal",
    "SOOS CREEK HATCHERY": "Green River",
    "CR HATCHERY": "Green River",
    "ICY CR HATCHERY": "Green River",
    "PALMER HATCHERY": "Green River",
    "GARRISON HATCHERY": "Chambers Creek",
    "MINTER CR HATCHERY": "Minter Creek",
    "NASELLE HATCHERY": "Naselle River",
    "FOSTER RD TRAP": "Elochoman River",
    "BEAVER CR HATCHERY": "Elochoman River",
    "ELOCHOMAN SILL TRAP": "Elochoman River",
    "COWLITZ SALMON HATCHERY": "Cowlitz River",
    "COWLITZ SALMON HATCH": "Cowlitz River",
    "COWLITZ TROUT HATCH": "Cowlitz River",
    "COWLITZ TROUT HATCHERY": "Cowlitz River",
    "COWLITZ SALMON": "Cowlitz River",
    "KALAMA FALLS HATCHRY": "Kalama River",
    "KALAMA FALLS HATCHERY": "Kalama River",
    "FALLS HATCHERY": "Kalama River",
    "FALLERT CR HATCHERY": "Kalama River",
    "MODROW TRAP": "Kalama River",
    "LEWIS RIVER HATCHERY": "Lewis River",
    "MERWIN DAM FCF": "Lewis River",
    "MERWIN HATCHERY": "Lewis River",
    "SPEELYAI HATCHERY": "Lewis River",
    "LYONS FERRY HATCHERY": "Snake River",
    "MARBLEMOUNT HATCHERY": "Skagit River",
    "HURD CR HATCHERY": "Dungeness River",
    "DUNGENESS HATCHERY": "Dungeness River",
    "DAYTON ACCLIMA. POND": "Touchet River",
    "TUCANNON HATCHERY": "Tucannon River",
    "EASTBANK HATCHERY": "Columbia River - Rocky Reach Dam",
    "CHIWAWA HATCHERY": "Chiwawa River", #<-- cool spots
    "SUNSET FALLS FCF": "Skykomish River",
    "WALLACE R HATCHERY": "Wallace River",
    "SOLDUC HATCHERY": "Sol Duc River",
    "KENDALL CR HATCHERY": "North Fork Nooksack River",
    "BAKER LK HATCHERY": "Baker Lake/Baker River",
    "CEDAR RIVER HATCHERY": "Cedar River",
    "REITER PONDS": "Skykomish River",
    "BOGACHIEL HATCHERY": "Bogachiel River",
    "WASHOUGAL HATCHERY": "Washougal River",
    "WASHOUGAL RIVER FISH": "Washougal River",
    "WASHOUGAL RIVER": "Washougal River",
    "WASHOUGAL RIVER FISH WEIR": "Washougal River",
    "SKAMANIA HATCHERY": "Washougal River",
    "WHATCOM CR HATCHERY": "Whatcom Creek",
    "SAMISH HATCHERY": "Samish River",
    "TOKUL CR HATCHERY": "Snoqualmie River",
    "ISSAQUAH HATCHERY": "Issaquah Creek",
    "VOIGHTS CR HATCHERY": "Puyallup River",
    "TUMWATER FALLS HATCH": "Deschutes River",
    "TUMWATER FALLS HATCHERY": "Deschutes River",
    "TUMWATER FALLS": "Deschutes River",
    "GLENWOOD SPRINGS": "Orcas Island",
    "MORSE CREEK HATCHERY": "Elwha River",
    "ELWHA HATCHERY": "Elwha River",
    "HUMPTULIPS HATCHERY": "Humptulips River",
    "MAYR BROTHERS REARIN": "Wishkah River",
    "LK ABERDEEN HATCHERY": "Chehalis River",
    "WYNOOCHEE R DAM TRAP": "Wynoochee River",
    "TACOMA POWER": "Wynoochee River",
    "BINGHAM CR HATCHERY": "Satsop River",
    "SATSOP SPRINGS PONDS": "Satsop River",
    "FORKS CREEK HATCHERY": "Willapa River",
    "NEMAH HATCHERY": "Nemah River",
    "GRAYS RIVER HATCHERY": "Grays River",
    "NORTH TOUTLE HATCHRY": "Toutle River",
    "NORTH TOUTLE HATCHERY": "Toutle River",
    "PRIEST RAPIDS HATCHERY": "Columbia River - Priest Rapids Dam",
    "RINGOLD SPRINGS HATCHERY": "Columbia River - Priest Rapids Dam",
    "RINGOLD SPRINGS": "Columbia River - Priest Rapids Dam",
    "METHOW HATCHERY": "Methow River",
    "WHITEHORSE POND": "Stillaguamish River",
    "WELLS HATCHERY": "Columbia River - Wells Dam",
    "SKOOKUMCHUCK HATCHERY": "Skookumchuck River",
    "SKOOKUMCHUCK HATCHRY": "Skookumchuck River",
    "MCKERNAN HATCHERY": "Skokomish River",
    "CHELAN HATCHERY": "Chelan River",
    "CHELAN PUD HATCHERY": "Chelan River",
    "SPOKANE HATCHERY": "Spokane River",
    "LK WHATCOM HATCHERY": "Whatcom Lake",
    "OMAK HATCHERY": "Okanogan River",
    "TWISP ACCLIMATION PD": "Methow River",
    "COTTONWOOD CR POND":"Cottonwood Creek Pond",
    "GRAYS RIVER WEIR":"Grays River",
    "Eells Springs":"Skokomish River",
    
}


# --- Stock_BO Map ---
stock_corrections = {
    "HATCHERYPriest Rapids- H": "Priest Rapids- H",
    "Skamania Hatchery WEIR Stock- H": "Skamania Hatchery Stock- H",
    "FISH WEIRWashougal River- H": "Washougal River- H",  
    "FISH WEIRWashougal River- W": "Washougal River- W",
    "205- W":"I-205- W",
    "SF- H":"Nooksack River -SF- H",
    "SF- W":"Nooksack River -SF- W",
    "FISH WEIRSkamania Hatchery Stock- H":"Skamania Hatchery Stock- H",
    "HATCHERYRingold Hatchery Stock- H":"Ringold Hatchery Stock- H",
    "HATCHERYPriest Rapids- M":"Priest Rapids- M",
    "HATCHERYPriest Rapids- U":"Priest Rapids- U",
    "HATCHERYWells- H":"Wells- H",
    "HATCHERYUnknown Stock- W":"Unknown Stock- W",
    "HATCHERYUnknown Stock- H":"Unknown Stock- H",
    "HATCHERYRingold- H":"Ringold- H",
    "HATCHERYHanford Reach- W":"Hanford Reach- W",
    "FISH WEIRSkamania- H":"Skamania- H",
    "Cowlitz River Hatchery HATCHERY Stock- H":"Cowlitz River Hatchery Stock- H",
    "OR- H":"Big Creek, OR- H",
    "Lake Aberdeen Stock- H":"Lake Aberdeen Hatchery Stock- H",
    "":"",
    "":"",
    "":"",
    "":"",
    "":"",
}

count_data_ignorepatterns = [
    r"(?i)Hatchery\. Final in-\s*",
    r"(?i)Hatchery\. Brood Year\s*",
    r"(?i)Aberdeen Hatchery\.\s*",
    r"(?i)Ponds\.Final in-season\s*",
    r"Salmon Hatchery\.\s*",
    r"Shipped to Speelyai\s*",
    r"for BY 2022\s*",
    r"Released into land-\s*",
    r"Shipped to Reiter\s*",
    r"Shipped to Palmer\s*",
    r"season estimate\.\s*",
    r"locked lake\.\s*",
    r"lakes\.\s*",
    r"lakes\s*",
    r"lake\.\s*",
    r"Hatchery\.\s*",
    r"Hatchery\s*",
    "",
    "",
]

# lookup_maps.py — near the bottom or wherever you keep correction maps

hatchery_name_corrections = {
    "RINGOLD SPRINGS HATCHERYP": "RINGOLD SPRINGS HATCHERY",
    # Add more as needed...
}

Stock_BO_corrections = {
    "RINGOLD SPRINGS HATCHERYP": "RINGOLD SPRINGS HATCHERY",
    # Add more as needed...
}